<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.0.3</Version>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RepositoryUrl>https://github.com/possession-community/TnmsAdminUtils</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.121" ExcludeAssets="runtime" />
        <PackageReference Include="ModSharp.Sharp.Modules.LocalizerManager.Shared" Version="2.1.121" ExcludeAssets="runtime" />
        <PackageReference Include="TnmsPluginFoundation" Version="0.0.8" ExcludeAssets="runtime" />
        
        <!-- While Dev -->
<!--        <ProjectReference Include="..\..\TNMSPluginFoundation\TnmsPluginFoundation\TnmsPluginFoundation.csproj" ExcludeAssets="all" />-->
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modules\UiInteractions\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove=".gitignore" />
    </ItemGroup>

</Project>
