<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.0.3</Version>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RepositoryUrl>https://github.com/possession-community/TnmsAdminUtils</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.123" ExcludeAssets="runtime" />

        <ProjectReference Include="..\..\TNMSPluginFoundation\TnmsPluginFoundation\TnmsPluginFoundation.csproj" Private="false" ExcludeAssets="runtime" PrivateAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modules\UiInteractions\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove=".gitignore" />
    </ItemGroup>

    <Target Name="CopyPlugin" AfterTargets="Build" Condition="'$(MOD_SHARP_DIR)' != ''">
        <Message Text="Copying the plugin files to ModSharp modules directory" Importance="High" />
        <Copy SourceFiles="$(TargetDir)$(ProjectName).deps.json;$(TargetDir)$(ProjectName).dll;$(TargetDir)$(ProjectName).pdb" DestinationFolder="$(MOD_SHARP_DIR)\modules\$(ProjectName)\reload" />
        <Message Text="Successfully copied the plugin files" Importance="High" />
    </Target>

</Project>
